# Generated by Django 2.2.2 on 2019-06-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190621_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
